spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio
    username: root
    password: senha123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
